### PR TITLE
Changed implementation of rle to C++ to improve performance

### PR DESCRIPTION
**Pull request by doug-friedman**
As a heads up, my commit log got all messed up after the last merge so feel free to just take the commits from the top of the stack past my "Replacing this with USGS-R/master..."

I replaced usage of rle in calcEvents and calcChangeEvents with [Hadley's rle2 function written in C++](https://github.com/hadley/adv-r/blob/master/extras/cpp/rle.cpp) from his Advanced-R book. This yields about a 3-5x performance improvement using the benchmark script below.

I assumed that you're ok with including Rcpp in the package given the inclusion of RcppRoll, but feel free to reject otherwise.

```R
library(Rcpp)
library(microbenchmark)

sourceCpp(code='
// Taken from https://github.com/hadley/adv-r/blob/master/extras/cpp/rle.cpp
#include <Rcpp.h>
#include <algorithm>
using namespace Rcpp;

// [[Rcpp::export]]
List rle2(NumericVector x) {
  std::vector<int> lengths;
  std::vector<double> values;

  // Initialise first value
  int i = 0;
  double prev = x[0];
  values.push_back(prev);
  lengths.push_back(1);

  for(NumericVector::iterator it = x.begin() + 1; it != x.end(); ++it) {
    if (prev == *it) {
      // Same as previous so increment lengths
      lengths[i]++;
    } else {
      // Different, so add to values, and add 1 to lengths
      values.push_back(*it);
      lengths.push_back(1);

      i++;
      prev = *it;
    }
  }

  return List::create(_["lengths"] = lengths, _["values"] = values);
}
')


x = runif(1e3)

# Check equality of resulting vectors
r1 = rle(x)
r2 = rle2(x)
all.equal(r1$lengths, r2$lengths)
all.equal(r1$values, r2$values)


# Benchmark
rle_m = microbenchmark(
 rle_r = rle(x),
 rle_C = rle2(x)
)
rle_m


#plot(rle_m)
```

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
I'm ok bringing this in, but I'm not really following why this isn't a function available from another package already. Should we really be bringing in utility code like this just for performance sake?

**Comment by doug-friedman** [comment]
I agree that this should already be an available function from another library. I had initially considered intrle from bit, but that was unwieldy. 

I'll let you all decide from a design standpoint, but you could always give the user the option to use rle vs rle2 via an algorithm parameter similar to runmean from caTools (https://www.rdocumentation.org/packages/caTools/versions/1.17.1/topics/runmean).

**Comment by dblodgett-usgs** [comment]
Curious how @ldecicco-USGS and @jread-usgs feel about this from the perspective of R tools at USGS more generally.

**Comment by ldecicco-USGS** [comment]
This package has screamed `Rcpp` from the get-go, but no one around here has had the time to get it started. So personally, I have no problem with it. Looks good to me. My one minor quibble is that I've moved away from writing `demo`'s in replace of adding another vignette. See Hadley's note:

http://r-pkgs.had.co.nz/demo.html

**Comment by dblodgett-usgs** [comment]
Hah, that `demo` is from me, actually. It should probably go into a vignette or some other format. I checked in as a `demo` out of convenience only.

**Comment by tmills-usgs** [comment]
I am slightly concerned about bringing this in just for maintenance in the future.

I think this brings up a broader question of the performance focus. Clearly this was an issue with the previous package, but are we investing too much time in performance gains? If the gains don't translate to benefits that *significantly* affect real-world applications, then I think it is time to table these type of changes to the code and focus on the stats and theory, which are much more pressing problems in my opinion.

**Comment by dblodgett-usgs** [comment]
I tend to agree. We should probably leave a note that there are performance gains to be had in RLE, but for the time being, I want to keep the package SIMPLE so we can get this thing accross the review and cran finish line.

**Comment by tmills-usgs** [comment]
OK, a quick back of the envelope calculation looks like a gain on the order of 0.2 seconds for 10 years of record at 1000 sites. Given our use cases thus far this seems like an insignificant gain for added complexity.

Great job though @doug-friedman , I will definitely keep that one in my back pocket for the future.

**Comment by ldecicco-USGS** [comment]
Sounds good. In my head, I was thinking more the efficiency speed up from the very original code, but for those numbers, than yeah, not worth it.

**Comment by tmills-usgs** [comment]
@ldecicco-USGS 

In my re-write I spent some time vectorizing the old code where ever I could and also brought in dplyr and RcppRoll for some of the obvious aggregate %>% summarize stuff. So, the speed increased substantially just from those low-hanging fruit.

@doug-friedman solved one of the more difficult cases where I kept the loop in because I was not clever enough. So actually now I think all the old loops are gone.

**Comment by ldecicco-USGS** [comment]
Schnazzy! :100:

**Comment by tmills-usgs** [comment]
Hmm...

After further thought I am going to leave this open for now. The function using rle is used repeatedly so my basic benchmark is not really appropriate. 

I can't mess with this more today but I will leave this open and make an issue to do a proper benchmark of HITstats with and without the new rle2

**Comment by dblodgett-usgs** [comment]
I cleaned up the git history over in #119 I think we should close this and use that for future merge potential. Will want to use some of the conversation here in #116.

**Comment by dblodgett-usgs** [comment]
@tmills-usgs - Based on my benchmarking last night, there is more variability in other aspects of the hitstats calculation than there is optimization in RLE. I think go ahead and close this at will. Thanks for all the help, @doug-friedman, but we need to focus in on getting these stats vetted and getting the package released in it's new form.

**Comment by doug-friedman** [comment]
No worries!

**Pull request closed without merging**
