### PR TITLE
Getting the readme cleaned up and adding the research padge.

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
@ldecicco-USGS Seem reasonable? Pretty sure I'll need to update a few things in the readme once I get this PR merged, but this is coming along.

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
I don't know @dblodgett-usgs , tests only cover 98% of the code...

**Comment by dblodgett-usgs** [comment]
98.499% !!!

**Comment by ldecicco-USGS** [comment]
Do you want to remove the non-.Rmd  files from the vignette forlder? Or is that helping your vignette issues?

**Comment by dblodgett-usgs** [comment]
They'll be removed in my next PR... I have build tools set wrong.

**Pull request merged**
