### PR TITLE
Use "names = F" for performance of quantile(). Fixes #107

### LINKED ISSUE #107: Using the names argument with quantile
I don't have a strong opinion on this, but I thought it was worth mentioning that you can achieve a decent speed increase by setting the names argument to false with the quantile function (https://stat.ethz.ch/R-manual/R-devel/library/stats/html/quantile.html). Given the amount of times quantile is used, it could have a large effect on the efficiency of the code. However, this means that the results could only be referred to by numeric index which would reduce the clarity of the source code.

Here's a simple example that shows a 2x performance improvement just by removing the names.
```R
library(microbenchmark)

vec_100 = runif(100, 0, 10e3)

microbenchmark(
  names = quantile(vec_100, probs = seq(0.05,0.95,0.05), type=6),
  no_names = quantile(vec_100, probs = seq(0.05,0.95,0.05), type=6, names=F)
)
```

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
I need a better way to benchmark performance of end-to-end runs. I know this should have improved things, but once again, the differences are so small they don't seam to change the bulk run times when comparing one method to another. Regardless, I think this is a solid change that should improve performance generally.

### CODE REVIEW

**Comment by doug-friedman** [comment]
@dblodgett-usgs - Out of curiosity, how are you conducting benchmarks of different package versions?

I had put together a little code like this, but there's got to be a better way.

```R
## Local Run
library(EflowStats)
x <- sampleData[c("date","discharge")]


z1 = vector(length=10)

for(i in 1:10){
  ptm <- proc.time()
  hitOutTest1 <- hitAllStats(x=x,yearType="water",stats="all",pref="mean",drainArea=50)
  z1[[i]] = (proc.time() - ptm)["elapsed"]
}

summary(z1)

## Master Run
detach(package:EflowStats)
devtools::install_github("USGS-R/EflowStats")

library(EflowStats)
x <- sampleData[c("date","discharge")]


z2 = vector(length=10)

for(i in 1:10){
  ptm <- proc.time()
  hitOutTest2 <- hitAllStats(x=x,yearType="water",stats="all",pref="mean",drainArea=50)
  z2[i] = (proc.time() - ptm)["elapsed"]
}

summary(z2)


```

**Comment by dblodgett-usgs** [comment]
I create two branches, one of the old code one of the new. I switch from branch to branch rebuilding the package and run the same code with one or the other branch built. Bruit force I guess.

**Comment by dblodgett-usgs** [comment]
It was Friday afternoon and I felt like doing something mindless so I added tests for errors.

**Comment by dblodgett-usgs** [comment]
That was painful. Note to self, remember to pull down new changes from upstream before banging head against wall.

**Comment by dblodgett-usgs** [comment]
Bike race canceled so I finished out testing things as far as I can with the data we have on hand. There are a few edge cases of the timing stats that don't get hit... probably OK, but I wish we get get to 💯.

**Comment by dblodgett-usgs** [comment]
Woowoo! 99.578 rounds to 💯

**Comment by tmills-usgs** [comment]
So did this in-fact increase performance in a substantial way?

**Comment by dblodgett-usgs** [comment]
It was a small increase in performance, but to be honest, any performance increase at this point is going to be small. The package is in pretty good shape for what it does!

**Comment by tmills-usgs** [comment]
OK, I don't have a strong preference but I like the naming personally, if its already been changed then OK but the named quantiles makes the code a little more readable and less prone to accidentally using the wrong quantile

**Comment by dblodgett-usgs** [comment]
Yeah. naming is bring applied as a second step: https://github.com/USGS-R/EflowStats/pull/138/files#diff-2e0de00f0bf93d86240339524ffcf2c5R180

Realizing I could have used setNames() to do this in a little more clean way, but this works.

**Comment by tmills-usgs** [comment]
That looks good to me.
That is really bizarre that the naming within the function slows it down so much

**Comment by doug-friedman** [comment]
@tmills-usgs - Agreed, but it makes sense if you look at the source code since it runs a separate secondary function for naming.

https://github.com/SurajGupta/r-source/blob/master/src/library/stats/R/quantile.R#L102

**Comment by dblodgett-usgs** [comment]
Alright. I'm gonna :shipit: !!

**Pull request merged**
