### PR TITLE
Improving performance of waterYearDay

### PR DESCRIPTION
**Pull request by doug-friedman**
I removed the nested ifelse statements for something with less comparisons. The result is about a 1.75x performance improvement using the example provided.

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
👍 I'll pull this down and make sure it's good to go with my open refactor.

**Comment by doug-friedman** [comment]
Ok - it didn't look like you changed the name of the function based on your PR, but feel free to adjust

**Comment by dblodgett-usgs** [comment]
No, it was all good with the changes I'd made. I would be curious if you could follow up on the question I had regarding the leap day code... 
> Should we be testing specifics for the leapYearDay function? I'm not following the logic here: https://github.com/USGS-R/EflowStats/blob/master/R/waterYearDay.R#L20

**Comment by doug-friedman** [comment]
Sure! 

I tried to match the logic of the original code which delineated Julian days into four cases.  In terms of testing, you would likely want to test each of those cases (detailed below).

- Leap Year / Julian Day >= 275  --------------> should become Julian Day - 274 _(Case 1)_
- Leap Year / Julian Day < 274 ----------------> should become Julian Day + 92  _(Case 2)_
- Not a Leap Year / Julian Day >= 274 --------> should become Julian Day - 273 _(Case 3)_
- Not a Leap Year / Julian Day < 273 ----------> should become Julian Day + 92 _(Case 4)_

For reference, here's how I worked out the logic in R originally:
```R
         jday = lubridate::yday(x)
        yrs_leap = lubridate::leap_year(x)
        gt_275 = jday >= 275
        gt_274 = jday >= 274

        jday[yrs_leap & gt_275] = jday[yrs_leap & gt_275] - 274 # Case 1
        jday[yrs_leap & !gt_275] = jday[yrs_leap & !gt_275] + 92 # Case 2

        jday[!yrs_leap & gt_274] = jday[!yrs_leap & gt_274] - 273 # Case 3
        jday[!yrs_leap & !gt_274] = jday[!yrs_leap & !gt_274] + 92 # Case 4

```

Line 20 of the new code simply collapses the check for cases 1 and 3 into a single line by using the fact that logical variables become 0/1 in R when used in arithmetic.


```R
        jday = lubridate::yday(x)
        yrs_leap = lubridate::leap_year(x)
        gt_lp275 = jday >= (274 + yrs_leap)

        jday[gt_lp275] = jday[gt_lp275] - (273 + yrs_leap[gt_lp275]) # Cases 1 and 3
        jday[!gt_lp275] = jday[!gt_lp275] + 92   # Cases 2 and 4

```

**Comment by dblodgett-usgs** [comment]
OK, I follow now. So the tests are put here: https://github.com/USGS-R/EflowStats/pull/131/commits/8f7557db067e71c4721c40b104da1eb8a094a201 hit all this because they include days before and after leap day in both leap and non leap years right?

**Comment by doug-friedman** [comment]
Yup exactly.

**Comment by dblodgett-usgs** [comment]
Last question... what is this line trying to do? https://github.com/USGS-R/EflowStats/blob/master/R/waterYearDay.R#L18 It's adding 274 to a boolean. Somehow it's not breaking tests, which is why I felt ok merging, but that doesn't seem right.

**Comment by dblodgett-usgs** [comment]
Oh, wait, I re-read your comment and I think I follow now. Didn't realize true/false become 0/1.

**Pull request merged**
