### PR TITLE
Streamlined magAverage

### PR DESCRIPTION
**Pull request by doug-friedman**
I was able to improve the performance of the function by doing the following:
- Switched over to mean.default (faster for smaller vectors)
- Added a preferences check
- Removed calculation of unnecessary statistics
- Removed use of CV function as it required re-calculating the mean 
- Reused median calculations where possible
- Streamlined similar dplyr calls
- Fixed documentation whitespace

Feel free to edit as make sense.

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
In general, as we work this package forward, I want to make sure that it has testing on individual functions. Looks like this didn't break the existing characterization tests for the htStats function, but it would be good to implement tests for all the behavior we expect the package to have. As long as @tmills-usgs is cool, I think we should go ahead and merge this, but as we go forward, atomic changes should come along with atomic tests. This test is an example of what I hope we can come up with: https://github.com/dblodgett-usgs/EflowStats/blob/b797dfee03a40b35bec8ffc55532075b39bfdb67/tests/testthat/test_dataCheck.R

**Comment by doug-friedman** [comment]
@dblodgett-usgs  - Agreed x 100. I think testing individual functions is key to identifying bugs early and often.

**Comment by dblodgett-usgs** [comment]
No worries. And thanks so much for the contributions!!!!

**Comment by doug-friedman** [comment]
No problem!

**Comment by doug-friedman** [comment]
Thanks!

**Pull request merged**
