### PR TITLE
Refactor Function Names... drastic but awesome!

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
Also did a bunch of clean up on the tests, data, and got vignette docs into the right place for the package. Yum.
screen shot 2017-05-13 at 4 26 38 pm

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
Now includes @doug-friedman's latest. Should we be testing specifics for the leapYearDay function? I'm not following the logic here: https://github.com/USGS-R/EflowStats/blob/master/R/waterYearDay.R#L20

**Comment by dblodgett-usgs** [comment]
@doug-friedman I was so confused that I decided to mark up this function with some very expressive comments. Make sense? See latest commit on this PR.

**Comment by doug-friedman** [comment]
The new comments look great! That's a really good addition for maintaining this long-term.

**Comment by tmills-usgs** [comment]
:hankey: 

Coverage decreased 0.01%, this will not stand

Joking, I looked over the changes and pulled them down and no issues so looks good to me

**Pull request merged**
